# Generated by Django 5.2.7 on 2025-11-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='')),
                ('location', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True, default='Unknown')),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('severity_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=50)),
                ('referrer_url', models.TextField(blank=True, default='')),
                ('device', models.CharField(blank=True, default='Unknown Device', max_length=255)),
                ('path', models.CharField(blank=True, default='/', max_length=255)),
                ('verb', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('response_status_code', models.IntegerField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='activity_lo_user_id_6e217e_idx'), models.Index(fields=['timestamp'], name='activity_lo_timesta_34d677_idx'), models.Index(fields=['severity_level'], name='activity_lo_severit_2c2493_idx')],
            },
        ),
    ]
