# Generated by Django 5.2.7 on 2025-11-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_lo_user_id_6e217e_idx',
        ),
    ]
