# Generated by Django 5.2.7 on 2026-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_catalog_cat_is_acti_7dd635_idx'),
        ('products', '0004_alter_product_category'),
        ('stores', '0002_remove_store_commission_rate_alter_store_store_owner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'created_at'], name='products_pr_categor_70227a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created_at'], name='products_pr_status_36c7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
    ]
