# Generated by Django 5.2.7 on 2026-02-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_price_productvariant_is_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discount_amount',
        ),
    ]
