# Generated by Django 5.2.7 on 2026-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_discount_price_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
