# Generated by Django 5.2.7 on 2026-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_specification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_default', 'created_at'], name='products_pr_product_b3692c_idx'),
        ),
    ]
