# Generated by Django 5.2.7 on 2026-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'display_order'], name='catalog_cat_is_acti_7dd635_idx'),
        ),
    ]
