# Generated by Django 5.2.7 on 2025-12-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingaddress_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
    ]
