# Generated by Django 5.2.7 on 2026-01-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(help_text='e.g. Inside Dhaka, Outside Dhaka', max_length=100, unique=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment'), ('bank_transfer', 'Bank Transfer')], default='cash_on_delivery', max_length=30),
        ),
    ]
