# Generated by Django 5.2.7 on 2026-01-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='orders.shippingconfiguration'),
        ),
    ]
