# Generated by Django 5.2.7 on 2026-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
