# Generated by Django 5.2.7 on 2026-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
