# Generated by Django 5.2.7 on 2025-11-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('nid_card_image', models.ImageField(upload_to='store_owner/nid_cards/')),
                ('store_details', models.TextField()),
                ('trade_license', models.ImageField(upload_to='store_owner/trade_license/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('nid_card_pic', models.ImageField(upload_to='vendor/nid_cards/')),
                ('product_details', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, upload_to='vendor/product_images/')),
                ('trade_license', models.ImageField(blank=True, null=True, upload_to='vendor/trade_license/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
