# Generated by Django 5.2.7 on 2025-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customer_storeowner_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='nid_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_owner/nid_cards/'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='trade_license',
            field=models.ImageField(blank=True, null=True, upload_to='store_owner/trade_license/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='nid_card_pic',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/nid_cards/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/product_images/'),
        ),
    ]
