# Generated by Django 5.2.7 on 2025-11-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_storeowner_status_vendor_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nid_card_image', models.ImageField(blank=True, null=True, upload_to='staff/nid_cards/')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='authentication.storeowner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
