# Generated by Django 5.2.7 on 2025-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='store_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
