# Generated by Django 5.2.7 on 2025-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_storeowner_store_name_vendor_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeowner',
            name='store_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
