# Generated by Django 5.2.7 on 2025-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_storeowner_store_name_alter_vendor_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeowner',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='store_name',
        ),
    ]
