# Generated by Django 5.2.7 on 2026-01-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_storeowner_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='authentication.vendor'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='store_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='authentication.storeowner'),
        ),
    ]
