"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).parents[2]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    'corsheaders',
    'rest_framework',
    'silk',
    'rest_framework_simplejwt',
    "rest_framework_simplejwt.token_blacklist",
    'django_celery_beat',
    'django_celery_results',
    # custom apps
    'apps.authentication',
    'apps.authorization',
    'apps.activity_log',
    'apps.products',
    'apps.catalog',
    'apps.stores',
    'apps.cart',
    'apps.orders',
    'apps.payments',
    'apps.blogs',
    'apps.notifications',
    'apps.review',
    'apps.wishlist',
    'apps.coupons',
    'apps.admin_dashboard',
    'apps.company_dashboard',
    'apps.vendors_dashboard',
    'apps.contacts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'apps.authentication.middleware.JWTMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 3rd party middleware
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        "NAME": "apps.authentication.validators.SimplePasswordValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# Language and time setting
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'  # Use local timezone
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Collected files

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User model setting
AUTH_USER_MODEL = 'authentication.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
    'rest_framework.renderers.JSONRenderer',
    'rest_framework.renderers.BrowsableAPIRenderer', 
],
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework_simplejwt.authentication.JWTAuthentication'],
    'EXCEPTION_HANDLER': 'apps.authentication.utils.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',  # Throttles per user
        # Throttles for unauthenticated users
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '80/minute',  # Limit to 80 requests per minute for authenticated users
        'anon': '60/minute',  # Limit to 60 requests per minute for anonymous users
    }
}

# cors setting
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


# max file size settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024      # 50MB per file
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024      # 50MB total per request


# Create logs directory if not exists
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

### LOGGER settings ###
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'myapp': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



DJANGO_ENV = os.getenv("DJANGO_ENV", default="development")
if DJANGO_ENV == "production":
    REDIS_LOCATION = os.getenv("REDIS_URL_PROD")
else:
    REDIS_LOCATION = os.getenv("REDIS_URL_DEV")


# Celery settings
CELERY_BROKER_URL = REDIS_LOCATION
result_backend = 'django-db'
accept_content = ['json']
task_serializer = 'json'
result_serializer = 'json'
timezone = 'Asia/Dhaka'
CELERY_TASK_REJECT_ON_WORKER_LOST = (DJANGO_ENV == 'development')


# Caching settings (Redis)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "COMPRESSOR_OPTIONS": {
                "min_length": 1024
            },
            "IGNORE_EXCEPTIONS": True,
        }
    }
}

CELERY_BEAT_SCHEDULE = {
    "flush-activity-logs-every-2-min": {
        "task": "apps.activity_log.tasks.flush_activity_logs",
        "schedule": crontab(minute="*/2"),
    },
    "delete-activity-logs-daily-midnight": {
        "task": "apps.activity_log.tasks.delete_activity_logs_older_than_one_month",
        "schedule": crontab(minute=0, hour=0),  # 12:00 AM daily
    },
    'release-holds-daily': {
        'task': 'apps.payments.tasks.release_holds_and_create_payouts',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'process-refunds-hourly': {
        'task': 'apps.payments.tasks.process_pending_refunds',
        'schedule': crontab(minute=0),  # Run every hour
    },
}

# Email settings for production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# JWT Configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # Short-lived access token
    # Refresh token valid for 15 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
    "ROTATE_REFRESH_TOKENS": True,  # Generates new refresh tokens on every refresh
    "BLACKLIST_AFTER_ROTATION": True,  # Old refresh tokens become invalid
    "ALGORITHM": "HS256",  # Secure hashing algorithm
    # Use Django's SECRET_KEY to sign JWTs
    "SIGNING_KEY": os.getenv("SECRET_KEY"),
    "AUTH_HEADER_TYPES": ("Bearer",),  # JWTs can still be passed in headers
    "AUTH_COOKIE": "access_token",  # Name of the cookie storing the access token
    # Name of the cookie storing the refresh token
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_USER_TYPE": "user_type",
    "AUTH_COOKIE_HTTP_ONLY": True,  # Prevent JavaScript from accessing cookies
    # Send cookies only over HTTPS (for production)
    "AUTH_COOKIE_SECURE": os.getenv("COOKIE_SECURE") == "True",
}




# SSLCommerz Configuration
SSLCOMMERZ_STORE_ID = os.getenv('SSLCOMMERZ_STORE_ID')
SSLCOMMERZ_STORE_PASSWORD = os.getenv('SSLCOMMERZ_STORE_PASSWORD')
SSLCOMMERZ_IS_SANDBOX = os.getenv('SSLCOMMERZ_IS_SANDBOX')

# Payment callback URLs (use ngrok for local testing)
SSLCOMMERZ_SUCCESS_URL = os.getenv('SSLCOMMERZ_SUCCESS_URL')
SSLCOMMERZ_FAIL_URL = os.getenv('SSLCOMMERZ_FAIL_URL')
SSLCOMMERZ_CANCEL_URL = os.getenv('SSLCOMMERZ_CANCEL_URL')
SSLCOMMERZ_IPN_URL = os.getenv('SSLCOMMERZ_IPN_URL')


