# Generated by Django 5.2.7 on 2025-11-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_staff'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='commission_rate',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_owner_stores', to='authentication.storeowner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stores', to='authentication.vendor'),
        ),
    ]
